services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test
    volumes:
      - postgresql-volume:/var/lib/postgresql/data
  config-server:
    build: ./configserver
    ports:
      - "8079:8079"
    networks:
      - common
  discovery-server:
    build: ./discoveryserver
    ports:
      - "8888:8888"
    networks:
      - common
  gateway-server:
    build: ./gatewayserver
    ports:
      - "8080:8080"
    restart: on-failure 

    depends_on:
      - discovery-server
      - config-server
    environment:
      - SPRING_CLOUD_CONFIG_PROFILE=prod
      - CONFIGURL=http://config-server:8079
    networks:
      - common

volumes:
  postgresql-volume: 
    name: postgresql-volume2 
  mongodb-volume:
    name: mongodb-volume2

networks:
  common:
    driver: bridge
